### ISSUE TITLE
Add name aliasing for boolean operations

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/GraphPPL.jl#17]
In https://github.com/biaslab/ReactiveMP.jl/pull/170 we added boolean operations to Bernoulli random variables. For user convenience, these operations should also be able to be performed using "regular" mathematical expressions, i.e.: 
```julia
# current implementation
z ~ AND(x, y)

# improved user interface
z ~ x && y
z = x && y
```

**Comment by bvdmitri** [comment]
Fixed with #18
