### ISSUE TITLE
Allow for `vague` in model specification

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/GraphPPL.jl#26]
Currently the `vague` function is not supported. From a user perspective I think it might be nice to allow for this, e.g.
```julia
 p ~ vague(Bernoulli)
```
Also relates to the `Uninformative` node. However, in this case a type is specified and inference can continue.

**Comment by wouterwln** [comment]
I find this quite vague (pun intended), what do you want this syntax to perform?

**Comment by bvdmitri** [comment]
`vague` is a function that defined in the `ReactiveMP`

```julia
julia> using ReactiveMP

julia> vague(Bernoulli)
Bernoulli{Float64}(p=0.5)
```

This is currently "broken", because you can do this
```julia
prior = vague(Bernoulli)
p ~ prior
```

but not directly
```julia
p ~ vague(Bernoulli)
```
