### ISSUE TITLE
Tuple creation for mixtures only works outside of node call

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/GraphPPL.jl#27]
When creating a mixture model of sorts, often you will be working with a vector of variables that has to be converted to a tuple for the mixture node, e.g.
```julia
a = randomvar(dim)
tuple_a = tuple(a...)
b ~ Mixture(z, a)
```
This creates some clutter, however, combining the last two lines gives an error
```julia
a = randomvar(dim)
b ~ Mixture(z, tuple(a...)) # fails with MethodError as_variable(...)
```
Aside from fixing the second case, perhaps this tuple creation step can be performed automatically, as to not burden the user with this.

**Comment by wouterwln** [comment]
You can now write this:

```
@model function mixture_demo(y)
    μ ~ Normal(0, 1)
    σ ~ vague(Gamma)
    local x
    for i in 1:10
        x[i] ~ Normal(μ, σ)
    end
    y ~ Mixture(tuple(x...))
end
```
And it will create a tuple factor node and an anonymous variable tuple(x...) that is attached to the Mixture and the tuple nodes. Is this something we can pattern match on @bvdmitri ?

![tmp](https://user-images.githubusercontent.com/13435238/233316005-9778507d-114b-4cf4-8e4a-31844f997a65.png)

**Comment by wouterwln** [comment]
After some playing around: This is broken if `x` is a tensor of variables (so not a vector), so I'll leave it open for now

**Comment by bvdmitri** [comment]
Why not just ?
```
y ~ Mixture(x)
```
I think in the current implementation it will be translated to something like:
```
y ~ Mixture(inputs = x)
```
which seems already fine to me.

Creating with `tuple(x...)` is a hacky old way to pass multiple variables to one edge and it is not necessarily the best one.

The following would be nice to support though
```julia
m1 ~ ...
m2 ~ ...
ms = (m1, m2)
y ~ Mixture(ms)
```

```julia
m1 ~ ...
m2 ~ ...
ms = [ m1, m2 ]
y ~ Mixture(ms)
```

```julia
m1 ~ ...
m2 ~ ...
y ~ Mixture([ m1, m2 ])
```

```julia
m1 ~ ...
m2 ~ ...
y ~ Mixture(( m1, m2 ))
```

**Comment by wouterwln** [comment]
As of right now, this works for tuples, not for arrays:

```
@model function mixture_test()
    m1 ~ Normal(0, 1)
    m2 ~ Normal(2, 1)
    m = (m1, m2)
    y ~ Mixture(m)
end
```

gives the same as:

```
@model function mixture_test()
    m1 ~ Normal(0, 1)
    m2 ~ Normal(2, 1)
    y ~ Mixture((m1, m2))
end
```
![tmp](https://user-images.githubusercontent.com/13435238/234520719-bdbb4db9-f635-4567-b688-2f43fd19906e.png)

With arrays, GraphPPL will attempt to create a new constant multivariate RV without checking what is inside:

```
@model function mixture_test()
    m1 ~ Normal(0, 1)
    m2 ~ Normal(2, 1)
    m = [m1, m2]
    y ~ Mixture(m)
end
```

gives:

![tmp](https://user-images.githubusercontent.com/13435238/234520964-30930df8-a2df-4ed4-b321-868cdb915a4e.png)

**Comment by bvdmitri** [comment]
I would say that there should not be any difference between tuples or arrays in this case. If you dispatch on `Tuple` somewhere maybe you can also dispatch on `AbstractArray`?

**Comment by wouterwln** [comment]
That works, I dispatch on `AbstractArray{NodeLabel} such that if you have `x ~ Normal([0,0] , [1 0; 0 1])` creates 2 variables instead of 8.

**Comment by bartvanerp** [comment]
@bvdmitri Indeed, if we could just omit this `tuple` stuff, then that would be even better
