### ISSUE TITLE
`RequireMessage` errors when interface name equals existing variable

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/GraphPPL.jl#32]
Consider the node 
```Julia
@node DemoNode Deterministic [ out, z ]
```
used in the partial model 
```
z ~ ...
y ~ DemoNode(z) where { pipeline = RequireMessage(z = ...) }
```
The model construction in this case will fail with the error: `Invalid name 'z' for new random variable. 'z' has already been initialized with the '=' operator.` This error is caused by the interface having the same name as the variable.
Renaming the variable `z` in the model solves the issue for now.

**Comment by wouterwln** [comment]
As of the current implementation, the `model` macro will never go into the `where` clause and instead immediately pass this to the underlying `DemoNode` node, so I assume this issue is fixed.
