### ISSUE TITLE
Uninformative error message in case of misspelled input arguments

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/GraphPPL.jl#76]
Consider 
```julia
@model function foo(x, y, privet)
    y ~ Normal(x, privet)
end

model = create_model()
ctx = context(model)
x = getorcreate!(model, ctx, :x, nothing)
y = getorcreate!(model, ctx, :y, nothing)
graph = make_node!(model, ctx, foo, y, (x = x, privte = 2); debug=true)
```

It fails with
```
AssertionError: length(missing_interface) == 1
```

because I misspelled `privet` with `privte`.

Same happens if I give extra arguments, e.g.
```julia
graph = make_node!(model, ctx, foo, y, (x = x, c = 2, d = 3, hello = 4, blabla = 5); debug=true)
```

The error message can be improved.

**Comment by wouterwln** [comment]
Should be fixed now. By the way, in your code example, `graph` will contain the `NodeLabel` `y` instead of containing the graph, since `make_node!` returns the left-hand-side of the tilde operation (because it evaluates the function if we can and returns the result)
