### ISSUE TITLE
Use of arbitrary distributions from `Distributions.jl`

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/GraphPPL.jl#79]
As discussed, it should be possible for users to use arbitrary distributions from `Distributions.jl`, without them needing to be defined in `RxInfer.jl`. Here just a reminder: As shown, this will require some lines of code, once the new `GraphPPL` version gets integrated in `RxInfer`. Would be great if the interface names get automatically adopted from the fieldnames in `Distributions.jl`.

**Comment by bvdmitri** [comment]
We definitely put this either in RxInfer or in an extension (if Distributions is loaded by a user, then we could define extra functions, this is new in 1.9)

**Comment by wouterwln** [comment]
I merged a PR that should implement the extension. @bvdmitri are you aware of any way in which I can test this or should we leave it be?

**Comment by wouterwln** [comment]
There are slight issues with this, as not all distributions from `Distributions.jl` have their interfaces as their `struct` fields (for example, a `Dirichlet` distribution has the following interfaces:
```julia
julia> GraphPPL.interfaces(Dirichlet, 1)
(:out, :alpha, :alpha0, :lmnB)
```
We can implement these "special" cases in the extension as well, but that kind of defies the point of this extension. Any suggestions?

**Comment by bvdmitri** [comment]
@wouterwln I think you can load `Distributions` in the tests and try to create an arbitrary graph with some arbitrary distribution and test that interfaces match your expectations. 

With the second issue about differences in the struct fields and desired interfaces it will happen more often I believe. You should look into the `params` method, but I'm not sure how to get actual names. That might require some manual work indeed.

**Comment by wouterwln** [comment]
This is as fixed as it's going to be. I'm going to close this to clean up the overview of open issues
